# Site settings
title: Improving computational performance with algorithm engineering
email: kirill.mueller@ivt.baug.ethz.ch
description: "This website is an entry point for packages and documentation for my submission to useR! 2015."
baseurl: ""
url: "http://krlmlr-useR15.github.io"

# Build settings
markdown: kramdown
permalink: pretty
