# Site settings
title: Improving computational performance with algorithm engineering
author: Kirill Müller
username: krlmlr
email: kirill.mueller@ivt.baug.ethz.ch
description: "This website is an entry point for packages and documentation for my submission to useR! 2015."
baseurl: ""
url: "http://krlmlr-useR15.github.io"
date: 2015-07-01 14:15:51 UTC

# Build settings
markdown: kramdown
permalink: pretty
